[project]
name = "tetris"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.1",
    "pygame>=2.6.1",
    "pygame-ce>=2.5.5",
]
